name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.100-preview.5.25277.114'

      - name: Display dotnet version
        run: dotnet --info

      - name: Build
        run: dotnet run run.cs
